services:
  app:
    build: .
    container_name: python-server
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/code
# Prettier stop pushing my code up! >:(

# Checking Docker Version: docker --version
# Want to check images?  docker images
# Getting container's info: docker ps -a
# Got a docker file? initiate the continer's settings : docker build -t <ImageName>
# run the main container's process: docker run <ImageName>
# Stop the main container process: docker stop <ImageName>
# Terminate the main container process: docker kill <ImageName>
# Delete the container: docker rm <ImageName>
