services:
  app:
    build: .
    container_name: python-server
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/code
# Prettier stop pushing my code up! >:(

# Checking Docker Version: docker --version
# Want to check images?  docker images
# Checking container info: docker ps -a
# Got a docker file? build the image: docker build -t <ImageName>
#
#
#
